### ISSUE TITLE
Enable issue.

### ISSUE THREAD

**Issue by Joarell** [dj95/zjstatus#1]
Hi man!
I hope you are doing great!
Firstly, I would like to thank your efforts on this plugin!
So, I try to use, but unfortunately I didn't... Rsrsrsr.
As you can see on the image, I just couldn't reach the pane to enable the plugin access.
I try to navigate to the pane but no success at all.

Could you please give me some help?
I think I'm doing something wrong.
Have a nice day!
![ZJSTATUS](https://github.com/dj95/zjstatus/assets/42722369/eed5ea30-7a38-4818-8294-fe47b4539a33)

**Comment by dj95** [comment]
Hi @Joarell,

first of all thanks for your kind words!

It's a bit tricky with the statusbar and granting permissions. I've introduced a config parameter in v0.2.1, that can be used to enable navigation to the statusbar. It's called `first_start "true"`.

Here's an example:

```kdl
 pane size=1 borderless=true {
        plugin location="file:target/wasm32-wasi/debug/zjstatus.wasm" {
            format_left  "{mode} #[fg=#89B4FA,bold]{session} {tabs}"
            format_right "{datetime}"
            format_space ""

            first_start                "true"   # this is the important line
    }
}
```

After the first start the option can be disabled/removed again, but you may need it on updates.

I created a section in the README stating out this problem in the installation, but maybe that's the wrong place or it is written kinda unclear.

Hope the workaround fixes the issue for you.

**Comment by Joarell** [comment]
Perfect!
Now it's working!
Thank you for your prompt reply, my friend!
I really appreciate your work on this plugin!

Have a great day!

**Comment by umop3plsdn** [comment]
i added first_start "true" after the format_space and it still sticks with the asking for permission with y/n and I can't get it to accept it. Did something change?
