### ISSUE TITLE
feature: add optional indicator for when a pane is fullscreen'd

### ISSUE THREAD

**Issue by colemickens** [dj95/zjstatus#10]
Hi,

This looks very interesting. I haven't adopted it yet, but might! I am wondering if you would consider adding a widget for giving a visual indicator that the current pane is fullscreened.

**Comment by dj95** [comment]
Hi,

thank you for the feature request! I implemented additional formatting for the tab widget. There you are now able to format normal and active tabs also based on their fullscreen or sync status.

**Comment by colemickens** [comment]
So fast, thanks! I definitely have to set this up now :wink: !

**Comment by colemickens** [comment]
Took a second to [hack it into my nixcfg](https://github.com/colemickens/nixcfg/commit/90914d2dd8cbecda7f785f2bb833d55c3887347b) and I'm still playing with it, but this "sparks joy". Awesome, awesome work!

**Comment by dj95** [comment]
Thanks for the kind words! :) I really appreciate, that you like it.

Do you mind if I copy parts of your home-manager config into the Readme? Then the flake way and the home-manager way are documented
