### ISSUE TITLE
feature: add a hostname widget

### ISSUE THREAD

**Issue by colemickens** [dj95/zjstatus#11]
Hi,

It would be nice to have the hostname in the zellij status pane. I tend to open a new term emu and running `zellij` remotely when operating with a remote host.

I'm torn on this request, since I can just interpolate the hostname in using Nix, and I have the concept of a "hostname color" of sorts that doesn't really make sense as a widget, and I would be interpolating into the config with Nix anyway.

Curious if you have thoughts, or maybe other non-Nix users would like this?

**Comment by dj95** [comment]
Hi,

thanks for the suggestion. I think it would be helpful to have the hostname in the widget.

However, it is not that easy to achieve this. Plugins run in a WASM sandbox, which right now do not provide a way to obtain the hostname. It's similar to the timezone, which we also need to set explicitely.

Maybe we can achieve this in a later stage, e.g. when zellij plugins are able to execute commands.

**Comment by colemickens** [comment]
Aha, makes sense. Without knowing much about how Zellij plugins work, I guess Zellij could make it available through the wasm plugin api too? But again, maybe overkill.

Feel free to close this if you want.

**Comment by dj95** [comment]
I'll close this issue, since the feature is now available by utilising the `command_` widget with zjstatus 0.9.0 and zellij 0.39.0.

Hope this is ok for you as an acceptable solution for your feature request.
