### ISSUE TITLE
alt <[]> keymap not working

### ISSUE THREAD

**Issue by malishengo** [dj95/zjstatus#18]
when use default layout, PreviousSwapLayout, NextSwapLayout work well, but not working when layout is zjstatus

**Comment by dj95** [comment]
Hey,

please refer to this issue. It describes the solution how to properly configure layouts files, such that swap layouts will work.

https://github.com/dj95/zjstatus/issues/8#issuecomment-1727079906

**Comment by malishengo** [comment]
ok, thank you
