### ISSUE TITLE
Slant example and formatting

### ISSUE THREAD

**Issue by umop3plsdn** [dj95/zjstatus#27]
Not sure why it doesn't work when I try to run a multi format on a single line to change the color of . In your slanted example you have a couple examples where sending  tab_active              "#[fg=#181825,bg=#ffffff,bold,italic] {index}  {name} #[fg=#ffffff,bg=#181825]"  changes the  to make the slant illusion work. However when I try to do the same thing with command_1_format    "#[fg=#181825,bg=blue,bold]{stdout} #[fg=blue,bold,bg=#181825]" it just prints out the second one in text format instead of changing the colors again like you did on the previous ones. What could I be doing wrong?

**Comment by dj95** [comment]
Hi,

the command widget unfortunately supports only one format string. I've not implemented multiple format strings into most of the widgets for simplicity and performance reasons. You could try to add the format after the command widget in `format_left` or `format_right`.
