### ISSUE TITLE
Transparent Cell Color

### ISSUE THREAD

**Issue by mike-lloyd03** [dj95/zjstatus#34]
Is there a way to set a blank color for background or foreground so it inherits the colors from the terminal color scheme?

I'm playing with transparency in my terminal and I'd like the gaps between tabs to be transparent.
![image](https://github.com/dj95/zjstatus/assets/49411532/2dc475be-a630-45bc-9d01-50df3b7a1155)

**Comment by dj95** [comment]
It just works for the background color. Simply unset it or set it to `NONE`. Then it should be transparent. However, this will not work of the foreground color.

**Comment by mike-lloyd03** [comment]
Thanks. I'll give that a shot.
