### ISSUE TITLE
Ability to add space between the tab items 💅 

### ISSUE THREAD

**Issue by bphenriques** [dj95/zjstatus#35]
**Is your feature request related to a problem? Please describe.**
Thank you for the plugin! This helped me migrating my visuals from tmux to zellij. I pretty much liked it and worked for me. It isn't something fancy.
<img width="1507" alt="image" src="https://github.com/dj95/zjstatus/assets/4727729/5bc26796-6d9e-45e2-b65b-0bb60a1935be">

However, in order to have separators I had to include an extra spacing with no formatting (nix code):
```nix
      tab_normal   "#[fg=${yellow}] {index} #[fg=${brightWhite}] {name} #[] "
      tab_active   "#[bg=${yellow},fg=${black}] {index} #[bg=${brightBlack},fg=${white}] {name} #[] "
```

Notice how it ends with ` $[] "`.

**Describe the solution you'd like**
To make intent more clear, adding a `tab_separator` perhaps that defaults to empty String and allows, in my case, to set to `  `.

**Additional context**
I have other enhancements that I will track separately.

**Comment by dj95** [comment]
Hey,

thanks a lot for the suggestion. I've implemented the feature and it will be included in the next release.
