### ISSUE TITLE
💅 Improve non normal mode configuration

### ISSUE THREAD

**Issue by bphenriques** [dj95/zjstatus#36]
**Is your feature request related to a problem? Please describe.**
For me, I do need a visual indicator when I am in normal mode but I do want in other modes. However, to do that, I need to actually setup each mode as it defaults to `mode_normal`. This leads to some duplication in the config and perhaps a bit brittle if more modes appear. It is not a huge problem for me because I generate using nix but could be cleaner:
```nix
let 
  ...
  # https://zellij.dev/documentation/keybindings-modes.html
  nonNormalModes = ["locked" "resize" "pane" "move" "tab" "scroll" "search" "entersearch" "renametab" "renamepane" "session" "tmux"];
in
''
...
     pane size=1 borderless=true {
        plugin location="file:${pkgs.zjstatus}/bin/zjstatus.wasm" {
             ${lib.concatMapStringsSep "\n" (mode: ''mode_${mode} "#[bg=${green},fg=${black}] {name} "'') nonNormalModes}
        }
     }
...
''
```

Which lets me create the following visual:
Normal: 
<img width="1511" alt="image" src="https://github.com/dj95/zjstatus/assets/4727729/eb922de4-eaaa-4063-a0ab-11b98ba2ff56">

Non-Norma:
<img width="1509" alt="image" src="https://github.com/dj95/zjstatus/assets/4727729/abd1aaf6-bc17-41c8-977b-0daff07d5e44">

**Describe the solution you'd like**
Not sure as I do not know the code-base. More intuitive (perhaps not for others), would be to have a `mode_non_normal`. The behaviour would be:
- `mode_{mode}` would default to `mode_non_normal` if set.
- `mode_{mode}` would default to `mode_normal` if `mode_non_normal` is not set.
 
**Additional context**
N/A

**Comment by dj95** [comment]
Hey,

thanks a lot for the feedback! I've implemented the config key `mode_default_to_mode`, which is able to override the default to `normal` to a specific other mode. E.g. with `mode_default_to_mode "tmux"` the format of the `tmux` mode will be used for unconfigured modes.
