### ISSUE TITLE
No *.wasm for the latest realease

### ISSUE THREAD

**Issue by LudoPinelli** [dj95/zjstatus#38]
Maybe it has been forgotten in the process ^^

If not, I tried to compile it, but I have hundreds of "cannot find xxx in this scope" errors. I suppose that it's because it uses Rust 1.72 while I'm on 1.75 and the wasm32-wasi is not added to the 1.72 version of rustc when cargo download what's necessary from the 1.75 version?

Sorry if the question is stupid, I'm not yet familiar with Rust and its ecosystem unfortunately :) Thanks!

**Comment by dj95** [comment]
Indeed, I had uploaded it, but created the release with some impatience, such that the wasm file was missing. Sorry for that. I've added it to the release.

For compiling wasm, you need to add the wasm32-wasi target to your rust toolchain.

```bash
rustup target add wasm32-wasi
```

Then you should be able to compile it.
