### ISSUE TITLE
Add a flake.nix to build the package

### ISSUE THREAD

**Issue by cor** [dj95/zjstatus#4]
Including a nix shell is already great! But reproducibly building the package itself with Nix would be even better

**Comment by dj95** [comment]
That would be great! I agree. Unfortunately I do not have the knowledge how to properly compile rust with the wasm target in a flake or how to package them properly for zellij. 

Do you have any advice for me how to start? Or some resources I can refer to for learning purposes?

**Comment by dj95** [comment]
I found crane through your flake template for rust. It worked immediately for the wasm32-wasi target, which I struggled most with, when implementing the flake on my own.
