### ISSUE TITLE
Add `format_center`

### ISSUE THREAD

**Issue by mrdgo** [dj95/zjstatus#41]
**Is your feature request related to a problem? Please describe.**
I would like to create something like [tpipeline](https://github.com/vimpostor/vim-tpipeline) with zjstatus. Basically, it's all there. The only thing, I would love to see is having the mode and the tabs rendered in the center, so I can put nvims statusline parts to the left and right. Because, as of now, I need to "attach" the mode and tabs to the left - that makes it jump around a bit weirdly.

**Describe the solution you'd like**
A new configurable property `format_center` that renders its content to the center of zjstatus.

**Comment by dj95** [comment]
Hey, thanks a lot for the feature request. I've implemented it in v0.13.0.

**Comment by mrdgo** [comment]
Wow, thank you so much!
