### ISSUE TITLE
Can't still stick the bottom of `Alacritty` when drag the `Alacritty` to scale 

### ISSUE THREAD

**Issue by TheKissOfDragon** [dj95/zjstatus#47]
Can'tstill stick the bottom of `Alacritty` when dragging the `Alacritty` to scaling 

**To Reproduce**
1. dragging the `Alacritty` to scaling 
2. zjstatus can't still stick the bottom of `Alacritty`

**Expected behavior**
when dragging the `Alacritty` to scaling,  zjstatus can't still stick the bottom of `Alacritty` 

**Screenshots**
as the screenshot shown below:
<img width="1619" alt="image" src="https://github.com/dj95/zjstatus/assets/12746438/2eb40ffe-b00e-4e64-86ca-a0925a86e7ce">

**Desktop (please complete the following information):**
 - OS: Sonoma 14.2.1 (23C71)
 - Zellij version v0.39.2
 - Version latest version

**Comment by TheKissOfDragon** [comment]
OK, Thanks for your response so quickly. So you mean that to layout rendered incorrectly caused this issue? you mentioned that if set  `setting the TERM environment variables correctly`, the issue will occur, how to set TERM environment variables, could you give me a sample when you are free? Thanks  a lot

**Comment by dj95** [comment]
Can you please post your layout?

With the `TERM` var, you could check how it is set with `echo $TERM`. For alacritty, outside of zellij it should be set to `alacritty-direct` and in zellij to `xterm-256color`. At least this is how it is configured on my side for the demo video.

To set these variables, you need to configure them as environment variables in each of your programs. 

This is for alacritty for your config file:

```toml
[env]
TERM = "alacritty-direct"
``` 

This for zellij for the config file:

```javascript
env {
    TERM "xterm-256color"
}
```

Feel free to try it. Hopefully it will resolve the issue.

**Comment by TheKissOfDragon** [comment]
Thanks a lot. I did what you suggested. There is some improvement.

**Comment by dj95** [comment]
Is the issue fixed right now?

**Comment by TheKissOfDragon** [comment]
@dj95 Thanks for your great support
