### ISSUE TITLE
need for more widgets 

### ISSUE THREAD

**Issue by benzwt** [dj95/zjstatus#51]
Thanks to the command widget, I'm able to run an arbitrary action on zjstatus.
For me, a single command widget is not enough; I run a conky to monitor my system, but I need to monitor the stock as well.

I have conceived two approaches
* plugin based
    * users develop theirs own widgets and load into zjstatus 
* command widget with vector in mind
    * expanding the command widget with container such that it can hold multiple commands.
    
[
![zjstatus-featureRequest drawio](https://github.com/dj95/zjstatus/assets/1032178/7475060d-3f05-4ea8-8e42-d9f91223f56c)
](url)

**Comment by dj95** [comment]
I'll close this issue, as you are able to run multiple commands with several `command_{{name}}` widgets. Feel free to add any details, if I'm missing something.
