### ISSUE TITLE
Hide frames

### ISSUE THREAD

**Issue by rodrigopim** [dj95/zjstatus#53]
In the Zellij settings there is the option of not showing frames, but even configured not to display the frames, ZJstatus render frames when using more than one panel.

 Zjstatus could follow according to the configuration made in Zellij.

**Comment by dj95** [comment]
Hi,

unfortunately zellij plugins are not able to read the zellij configuration. The feature, that toggles pane frames must be **explicitely** set in zjstatus config. However, it is included in the example config.

Please follow the documentation for this feature: https://github.com/dj95/zjstatus/wiki/2-%E2%80%90-Configuration#hide-pane-frames-for-tabs-single-panes

If set to `false` or removed, zjstatus won't interfere with the pane borders.

**Comment by rodrigopim** [comment]
Thanks

**Comment by dj95** [comment]
I added now a hint to the example in the README. Hopefully it get's more transparent how it works.
