### ISSUE TITLE
Use specific version number instead of latest in the URL

### ISSUE THREAD

**Issue by steakhutzeee** [dj95/zjstatus#56]
**Is your feature request related to a problem? Please describe.**
When using the plugin with the URL method pointing to "latest" release https://github.com/dj95/zjstatus/wiki/1-%E2%80%90-Installation#automated-installation users need to clean the cache before an update because Zellij caches the plugin as specified here https://github.com/zellij-org/zellij/issues/967#issuecomment-2092662215

**Describe the solution you'd like**
Use specific version number instead of “latest”, in order to update flawlessly.
Like https://github.com/dj95/zjstatus/releases/download/v0.14.1/zjstatus.wasm

Thank you!

**Comment by dj95** [comment]
Hi, you can simply replace the URL with one of the URLs to the `zjstatus.wasm` file in the releases. The URL with latest in the docs can be used, if the update should proceed automatically, when the cache is cleared at some point.

You can also download the file of a release and point to it in a layout.
