### ISSUE TITLE
Great plugin

### ISSUE THREAD

**Issue by xtrasmal** [dj95/zjstatus#57]
I just wanted to say thanks!

**Comment by dj95** [comment]
Thanks a lot for the feedback! I really appreciate it. Hope you have some great time tinkering around with zellij and zjstatus.

**Comment by xtrasmal** [comment]
<img width="3440" alt="image" src="https://github.com/dj95/zjstatus/assets/1174877/2c2df307-ce3f-4d9d-95ae-209b1bc9a51e">

**Comment by dj95** [comment]
Looks really nice! I might use some things as inspiration for my daily setup. Really clean, how the tabs are separated with the slashes.

Feel free to write here in the issue (or as a discussion) or in the zellij discord, if you need some help with the zpipe command (or some feature is missing).
