### ISSUE TITLE
Cannot load the plugin

### ISSUE THREAD

**Issue by mostafaqanbaryan** [dj95/zjstatus#6]
Hi.
First of all, thank you for the great job you've done!
Unfortunately, I cannot use the plugin.
In zellij log I get:
```
INFO   |zellij_server::plugins   | 2023-09-11 13:33:01.855 [wasm      ] [zellij-server/src/plugins/mod.rs:137]: Wasm main thread starts
WARN   |zellij_utils::ipc        | 2023-09-11 13:33:02.972 [router    ] [zellij-utils/src/ipc.rs:222]: Error in IpcReceiver.recv(): InvalidMarkerRead(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })
ERROR  |zellij_client            | 2023-09-11 13:33:02.972 [router    ] [zellij-client/src/lib.rs:348]: Received empty message from server
```
And nothing.
I used the default config in the document and even added `first_start: "true"`, but didn't change anything.

**Comment by dj95** [comment]
Hi, first of all thanks!

Can you please provide some more details? Here's a quick list, that makes debugging a bit easier.

- zellij version
- plugin version
- is the plugin self compiled or downloaded
- used layout file
- where is the plugin (wasm file) located?

With these information I can try to reproduce your error. `first start` is not needed anymore.

**Comment by mostafaqanbaryan** [comment]
Of course!
- zellij version: `0.38.1`
- plugin version: `0.4.0`
- it's downloaded from release page
- I've tested with a few layouts:
```
layout {
    default_tab_template {
        children
        pane size=1 borderless=true {
            plugin location="file:/$HOME/dotfiles/zellij/plugins/zjstatus.wasm" {
                format_left  "{mode} #[fg=#89B4FA,bold]{session} {tabs}"
                format_right "{datetime}"
                format_space ""

                hide_frame_for_single_pane "true"

                mode_normal  "#[bg=#89B4FA] "
                mode_tmux    "#[bg=#ffc387] "

                tab_normal   "#[fg=#6C7086] {name} "
                tab_active   "#[fg=#9399B2,bold,italic] {name} "

                datetime        "#[fg=#6C7086,bold] {format} "
                datetime_format "%A, %d %b %Y %H:%M"
                datetime_timezone "Asia/Tehran"
            }
        }
    }
}
```
- FYI: layout name is `projects.kdl`, don't know if it matters
If you need anymore information, I'd be happy to help.

**Comment by mostafaqanbaryan** [comment]
> Can you test with the absolute path without `$HOME`? I'm not sure if zellij is able to resolve the reference.

Nope, didn't work.
If I load a plugin with wrong path, zellij says `ERROR IN PLUGIN`.
But if it's right, it'll close and echos `Received empty message from server`

**Comment by dj95** [comment]
Hmm, which OS do you use and how did you install zellij? I'll test it later then.

**Comment by mostafaqanbaryan** [comment]
- Pop!_OS 22.04 LTS
- Downloaded from release page

**Comment by dj95** [comment]
Unfortunately I cannot reproduce the issue :/ I've set up a fresh PopOS vm and downloaded the releases as you did. As you can see in the screenshot, it's working.

I've created sha256 sums of the files, so you are able to verify, if we use the same.

![20230911_20h01m54s_grim](https://github.com/dj95/zjstatus/assets/4348959/8bc4138c-be2d-4ff3-b9f0-045c4acddec8)

**Comment by mostafaqanbaryan** [comment]
> Unfortunately I cannot reproduce the issue :/ I've set up a fresh PopOS vm and downloaded the releases as you did. As you can see in the screenshot, it's working.
> 
> I've created sha256 sums of the files, so you are able to verify, if we use the same.
> 
> ![20230911_20h01m54s_grim](https://user-images.githubusercontent.com/4348959/267107523-8bc4138c-be2d-4ff3-b9f0-045c4acddec8.png)

Thank you for taking the time and testing.
Let me test again and check the sums, maybe I did something wrong.

**Comment by mostafaqanbaryan** [comment]
Oddly enough, everything's the same:
![image](https://github.com/dj95/zjstatus/assets/94293456/92ce5b07-63bf-46b2-88b0-e6bf924a45a2)
Maybe it has something to do with my setup.
Anyway, thank you for the time!

**Comment by dj95** [comment]
I were just able to recreate a similar issue with an older zellij version. Can you try to run zellij with the absolute path and then passing the arguments? Just in case there'a somewhere an older binary in $PATH. 

Otherwise I don't really have an idea, what goes wrong :/ sorry

**Comment by mostafaqanbaryan** [comment]
Unfortunately didn't work.
Looks like this happened [in here too](https://github.com/Nacho114/harpoon/issues/1).

**Comment by dj95** [comment]
Hi @mostafaqanbaryan ,

I don't know if you still bother with the problem, but I managed to reproduce it (by accident  😅) on macOS.

It happened, when I tried the current development version of zellij, which updated the WASM sandbox.

To fix the issue, I had to close all zellij instances and clean the cache under `~/Library/Caches/org.Zellij-Contributors.Zellij`. Under linux it should be at `~/.cache/zellij`.

Maybe it fixes the issue for you as well.

**Comment by mostafaqanbaryan** [comment]
> Hi @mostafaqanbaryan ,
> 
> I don't know if you still bother with the problem, but I managed to reproduce it (by accident  😅) on macOS.
> 
> It happened, when I tried the current development version of zellij, which updated the WASM sandbox.
> 
> To fix the issue, I had to close all zellij instances and clean the cache under `~/Library/Caches/org.Zellij-Contributors.Zellij`. Under linux it should be at `~/.cache/zellij`.
> 
> Maybe it fixes the issue for you as well.

I didn't even know there was a cache!
Removing the cache fixed it, Thank you!
