### ISSUE TITLE
New widget: Search

### ISSUE THREAD

**Issue by tranzystorekk** [dj95/zjstatus#60]
**Is your feature request related to a problem? Please describe.**

Using zellij's search utility gets harder with pane frames hidden, because the search term is no longer visible.

**Describe the solution you'd like**

I imagine a widget that appears in search mode and shows the search term - maybe with looks inspired from vim's backward search command: `?<search_term>`.

**Comment by dj95** [comment]
Thanks a lot for your feature request! 

Unfortunately, I don't find a way to catch the search term from zellij. However, I implemented some logic for the pane frames,  such that they are toggle when in search mode or when renaming a pane.

Additionally I added a feature for the tab widget, which makes it easier to rename them as you see the input and are able to theme the state additionally.

<img width="2992" alt="Screenshot 2024-05-25 at 11 32 32" src="https://github.com/dj95/zjstatus/assets/4348959/f33d9bfb-68e4-44b2-8dbd-aa0a4539ddbd">

Does this suite your feature request?

**Comment by tranzystorekk** [comment]
Yeah, that sounds like a good solution as well, thanks for taking the time!

**Comment by tranzystorekk** [comment]
Built and tested https://github.com/dj95/zjstatus/commit/c186c82cad5dac26c0a2214a9fc89c5ff2c4f112, works really nice!

**Comment by dj95** [comment]
Great! I'll then close this issue, as it will be released with the next releases.
