### ISSUE TITLE
how to have a unique color for the active tab among others

### ISSUE THREAD

**Issue by nbari** [dj95/zjstatus#63]
The color of all the tabs remains as the "tab_active" and is not reset after moving to another tab. 

This is how it looks when `tab #2` is active: (I was expecting tab 1 in white, tab 2 in orange and tab 3 in white) 
![image](https://github.com/dj95/zjstatus/assets/364199/055e14ca-32fc-4320-aa16-4d86b4ecbd27)

The more tabs the more confusing it gets because all reset to the same color:
![image](https://github.com/dj95/zjstatus/assets/364199/aa990106-4388-4d3d-a1ab-71d1bbda2986)

This is how it looks in tmux when `tab #1` is active, the others remain in white, and  if need to change to tab 3 the previous tab will change to white and the new to orange
![image](https://github.com/dj95/zjstatus/assets/364199/3eba9596-05d3-4ede-8480-300541b017ef)

If a new tab is added (became the active and it looks like):
![image](https://github.com/dj95/zjstatus/assets/364199/f1327e7e-597e-4c8f-9307-d471610ccf2a)

Any idea about how to achieve this?

I am using `zellij 0.40.1`

This is my config:

```
layout {
    default_tab_template {
        pane size=1 borderless=true {
            plugin location="https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm" {
                format_left   "{mode} #[fg=#FDB813]{session} {tabs}"
                format_right  "{command_uptime} {datetime}"
                format_space  ""

                border_enabled  "false"
                border_char     "-"
                border_format   "#[fg=#6C7086]{char}"
                border_position "top"

                hide_frame_for_single_pane "false"

                mode_normal  "#[bg=blue] "
                mode_tmux    "#[bg=#ffc387] "
                mode_tab     "#[fg=#fff] {name} "

                tab_normal   "#[fg=#fff] {name} "
                tab_active   "#[fg=#FDB813,bold,italic] {name} "

                command_uptime_command     "sh -c \"uptime | grep -o '..user.*'\""
                command_uptime_format      "#[fg=#5E81AC] {stdout}"
                command_uptime_interval    "30"
                command_uptime_rendermode  "static"

                datetime        "#[fg=#6C7086,bold] {format} "
                datetime_format "%H:%M:%S"
                datetime_timezone "Europe/Berlin"
            }
        }
        children
    }
}
```

Is there also a way to only show the number, not the word `Tab`? and preferably the command running in that tab (similar to tmux `1:zsh`) ?

**Comment by dj95** [comment]
You must specify full hex rgb with 6 chars after the `#`. Please consult the documentation for this. That's what I wrote the wiki for.

The word "Tab" comes from zellij. Therefore it's not possible to change it.

**Comment by nbari** [comment]
Hi @dj95 using full hex 6 chars makes it work, thanks.  I would suggest documenting this because when using 3 hex chars it works partially, at least the color changes and it is confusing, despite is common to represent colors with only 3 hex chars.
