### ISSUE TITLE
Indicator that I am in a full-screen zoom of a pane

### ISSUE THREAD

**Issue by ahkohd** [dj95/zjstatus#66]
Original issue here:
https://github.com/zellij-org/zellij/issues/3074

I see another plugin project has already implemented it: https://github.com/cristiand391/zj-status-bar/commit/062202b143b39a596924c9fec700e0038ff969da

Can this plugin also add support for this feature?

**Comment by dj95** [comment]
Hi and thanks for the feature request.

The fullscreen indicator is implemented for a long time. Please consult the documentation https://github.com/dj95/zjstatus/wiki/4-%E2%80%90-Widgets#tabs

**Comment by ahkohd** [comment]
@dj95 thanks very much!
