### ISSUE TITLE
Multiple Color Selection

### ISSUE THREAD

**Issue by MrWelsch** [dj95/zjstatus#68]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to select multiple colors for different text segments.
![image](https://github.com/dj95/zjstatus/assets/45096895/559d2c4b-c875-40d7-99ff-9691edcfbd7e)

**Describe the solution you'd like**
![image](https://github.com/dj95/zjstatus/assets/45096895/673e7693-8082-43bd-93e6-75f567c2838b)
I would like to recreate the theming I had in tmux, as shown in the picture.

**Comment by dj95** [comment]
Hi,

please take a look at the showcase discussions and some example layouts. It is currently possible and one of the screenshots depicts a similar theme. One screenshot of the post also shows the config, such that you can tinker around with this to get your look and feel.

**Comment by MrWelsch** [comment]
> Hi,
> 
> please take a look at the showcase discussions and some example layouts. It is currently possible and one of the screenshots depicts a similar theme. One screenshot of the post also shows the config, such that you can tinker around with this to get your look and feel.
> 
> Edit: also some widgets already support multiple theme directives

Hi,
thanks for pointing this out. It somehow doesn't seem to work with 'datetime'.

![image](https://github.com/dj95/zjstatus/assets/45096895/119826bd-ea6f-4a85-aec9-8063ae2f1c91)

![image](https://github.com/dj95/zjstatus/assets/45096895/e9f83e6d-1a48-4bca-9e94-864a2e911adc)

**Comment by dj95** [comment]
You should put the starting half circle before the date time widget.
