### ISSUE TITLE
Separate date and time formats

### ISSUE THREAD

**Issue by zDonik1** [dj95/zjstatus#70]
**Is your feature request related to a problem? Please describe.**
I would like to add some more formatting between the date and time.

**Describe the solution you'd like**
Either make date and time separate widgets, or replace `{format}` with `{date}` and `{time}` when describing the formatting for the date and time.

**Additional context**
For the latter solution to work multiple formatting directives should be supported in `datetime` field.
Related: https://github.com/dj95/zjstatus/issues/69 https://github.com/dj95/zjstatus/issues/40

**Comment by dj95** [comment]
Hi and thanks for your feature request.

It is implemented and will be released with the next version.
