### ISSUE TITLE
Add Modern “tmux2” Styled Solarized Dark Layout to Zjstatus

### ISSUE THREAD

**Issue by starkovv** [dj95/zjstatus#74]
Hello!

I’ve created a new layout for Zjstatus called [“tmux2”](https://github.com/starkovv/tmux2-zjstatus-layout) which features a modern, solarized dark theme. This layout offers a clean and informative status bar with elements such as the host OS icon, session name, and dynamic mode indicators. It enhances the existing “tmux” style layout by providing a more visually appealing and functional design.

I believe this layout could be a great addition to the existing examples in your repository. I’ve tested it extensively and found it to work best with the solarized dark terminal color theme.

Please consider including this layout in the repository. I’d be happy to submit a pull request with the configuration details.

Thank you for your hard work on Zjstatus!

**Comment by dj95** [comment]
Hi and thanks for your feedback! I really appreciate it.

Also thanks for your work on the layout. I'd be really happy to see your layout in the community showcase :) this way you also get the credits for your awesome layout!

**Comment by starkovv** [comment]
Hi @dj95,

Thanks for the quick response and the kind words!

I’d love to contribute my layout to the community showcase. Could you please guide me on the process? Should I open a pull request with the layout details, or is there another way you prefer to handle it?

Looking forward to your guidance.

**Comment by dj95** [comment]
Sure. The community case is in the discussions. You'll find it here: https://github.com/dj95/zjstatus/discussions/44

I'll link it also to the Readme in the next days, so it will be found easier :)

**Comment by dj95** [comment]
Thanks a lot for sharing!
