### ISSUE TITLE
Trying to check out zjstatus, but it fails

### ISSUE THREAD

**Issue by alekspickle** [dj95/zjstatus#78]
**Describe the bug**
Trying to check out zjstatus, but apparently it does not want to load :(
not sure if its a zjstatus thing or zellij bug, direct me if necessary

**To Reproduce**
1. run new session with zjstatus.wasm defined

**Expected behavior**
zjstatus would show as in screenshots

**Screenshots**
![Screenshot_20240723_164446](https://github.com/user-attachments/assets/32fb1a8a-cb37-47a4-bd8a-340bbbea4c36)

**Desktop (please complete the following information):**
 - OS: Linux
 - Zellij version: v0.40.1
 - Version: 0.17.0

**Layout**

How does the layout look like? Please copy it into a code block.

```kdl
layout {
    default_tab_template {
        children
        pane size=1 borderless=true {
            plugin location="file:~/.config/zellij/plugins/zj_status.wasm" {
                
            }
        }
    }
    tab name="☍ dev" {
        pane
    }
    tab name="ꆛconfig"{
        pane
    }
 }
```

**Additional context**
```
ERROR  |zellij_server::plugins::w| 2024-07-23 16:36:37.374 [async-std/runti] [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zellij-server-0.40.1/src/plugins/wasm_bridge.rs:1224]: failed to start plugin 0 for client 1

Caused by:
    0: failed to recover cache dir
    1: WebAssembly translation error: Error when converting wat: expected at least one module field
            --> <anon>:1:1
             |
           1 |
             | ^

```

**Comment by dj95** [comment]
Try to download it with wget. This works perfectly on my side. So I guess that's the problem, why it doesn't load.

Then we can close the issue, if it loads fine when downloaded manually

**Comment by alekspickle** [comment]
yep, you are completely right, my bad forgetting the redirect
Thank you so much!
