### ISSUE TITLE
status bar move left and blocked when open too many tabs

### ISSUE THREAD

**Issue by shdluan** [dj95/zjstatus#81]
when I open too many tabs, the status bar moved left and blocked, as below

When open 9 tabs:
![image](https://github.com/user-attachments/assets/f819966f-82e4-4279-94f3-60e3a66889bd)

When open an extra tab, the status bar like:
![image](https://github.com/user-attachments/assets/a75c1308-887e-4803-832d-a47eee257fbb)

the single number is second number of the date time
maybe put fold tabs on the agenda is a good idea

**Comment by dj95** [comment]
Hi and thanks for you bug report. This is a configuration issue.

You either need to restrict the amount of displayed tabs to a certain amount: https://github.com/dj95/zjstatus/wiki/4-%E2%80%90-Widgets#tabs

or hide parts of the statusbar that overlaps: https://github.com/dj95/zjstatus/wiki/3-%E2%80%90-Configuration#hiding-format-parts-on-over-length

**Comment by shdluan** [comment]
Thank you for your replay and I have learned it
good day!!


| |
Luan Shd
|
|
***@***.***
|
---- Replied Message ----
| From | Daniel ***@***.***> |
| Date | 8/28/2024 23:26 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [dj95/zjstatus] status bar move left and blocked when open too many tabs (Issue #81) |

Hi and thanks for you bug report. This is a configuration issue.

You either need to restrict the amount of displayed tabs to a certain amount: https://github.com/dj95/zjstatus/wiki/4-%E2%80%90-Widgets#tabs

or hide parts of the statusbar that overlaps: https://github.com/dj95/zjstatus/wiki/3-%E2%80%90-Configuration#hiding-format-parts-on-over-length
