### ISSUE TITLE
README installation steps out of date

### ISSUE THREAD

**Issue by Eloquencere** [dj95/zjstatus#84]
**Description**
I have a feeling that the README for the procedure of installation for non-nix cases seems to be out of date. From my inspection I found no `.wasm` file in the repo. I'm not sure if I'm missing something here.

**Comment by dj95** [comment]
Hi and thanks for your bug report.

I believe the Readme should be sufficient enough. It says: "Download the latest binary in the github releases.", which explains why you don't find it in the repo itself.

Without the releases, it's not obvious and trivial to version the wasm file. Therefore the wasm file is just appended to each release with the related changelog.
