### ISSUE TITLE
Option to always show frames

### ISSUE THREAD

**Issue by FelisNivalis** [dj95/zjstatus#94]
**Is your feature request related to a problem? Please describe.**

I would like to have an option to always show frames.

**Describe the solution you'd like**

I thought `hide_frame_for_single_pane` was what I want but it seems to be `show_frames_for_multiple_panes` actually.

Adding an option to show frames when there is only one pane should do what I want.

**Comment by dj95** [comment]
Hi and thanks for the feature request?

Do you want to always show the frames or just show them for one pane and disable them on multiple ones?

If you always want them, just disable `hide_frame_for_single_pane` and activate  the pane frames within the zellij config.

**Comment by FelisNivalis** [comment]
Hi thanks for the reply!

I want to always show the frames.

I tried and it didn't work.

I think it's because
```rust
    if (!frames_for_search && !frames_for_fullscreen && !frames_for_single_pane) && frame_enabled {
        toggle_pane_frames();
    }
```
in [frames.rs](https://github.com/dj95/zjstatus/blob/5d6ff93551882fddc7773f108470001fe87a5187/src/frames.rs#L43).

The frame is turned off when all the three booleans are false.

**Comment by dj95** [comment]
You need to turn all booleans off and then enable frames within the zellij config.kdl file. Then it should work. It's not a zjstatus thing.

**Comment by dj95** [comment]
I could reproduce the issue and fixed it with a new release. Thanks for the report! Nice catch! :)
