### ISSUE TITLE
Provide global configuration instead of define listing each configuration item in each layout file

### ISSUE THREAD

**Issue by ChenLuoi** [dj95/zjstatus#98]
I have a lot of layout files for different use cases. I had to define them separately in each layout file, and modify all files when the configuration changes.☹️
Is there a way to share zjstatus configuration across multiple layouts?
Global configuration may be a good idea, plz.

**Comment by dj95** [comment]
#Closing this issue as you've replied in the referenced issue, that plugin aliases fulfill the expected feature.
